baseurl: /
title: TkkrLab
theme: tkkrlab-mainroad
logo: /site_header.png

enableRobotsTXT: false
canonifyURLs: true
googleAnalytics: UA-610785-7

languages:
  nl:
    languageName: Nederlands
    weight: 1
  en:
    languageName: Engels
    weight: 2
  de:
    languageName: German
    weight: 3

defaultContentLanguage: nl
    
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  subtitle: "Makerspace Enschede"
  description: "TkkrLab hackerspace"
  powered_by: ""
  hide_author: true
  images: []
  author: "TkkrLab"
  avatar: "css/images/avatar.png"
  date_format: "02-01-2006"
  readmore: true
  post_navigation: true
  postSections: ["blog"]
  copyright: "Copyright 2023 - Stichting TkkrLab"
  widgets:
    search: false
    recent_articles: true
    recent_articles_num: 5
    tags: true
    tags_counter: false
    newsletter: true
    contact: true
    meta: true
    twitter: true
    social_facebook: "TkkrLab"
    social_twitter: "tkkrlab"
    social_github: "tkkrlab"
    social_youtube: "TkkrLab"
    social_instagram: "TkkrLab"
    social_linkedin: "company/tkkrlab/"
    

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/blog/"
      weight: 2
    - name: "Cybersaturday"
      url: "/cybersaturdays/cybersaturday"
      weight: 3
    - name: "Projecten"
      url: "/projects"
      weight: 7
    - name: "Deelnemer worden"
      url: "/deelnemer-worden"
      weight: 10
    - name: "Info"
      identifier: "info"
      url: "#"
      weight: 7
    - name: "Grafana: space statistieken"
      parent: "info"
      url: "https://grafana.tkkrlab.space"
      weight: 10
    - name: "How To's en handleidingen"
      parent: "info"
      url: "https://handleidingen.tkkrlab.space"
      weight: 11 
    - name: "Arduino cursus"
      parent: "info"
      url: "https://arduino.tkkrlab.space"
      weight: 12
