baseurl: /
title: TkkrLab
theme: airspace-hugo
enableRobotsTXT: false
canonifyURLs: true
defaultContentLanguage: nl
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: []

markup:
  goldmark:
    renderer:
      unsafe: true
  
params:
  subtitle: "Makerspace Enschede"
  description: "TkkrLab hackerspace"
  powered_by: ""
  hide_author: true
  images: []
  author: "TkkrLab"
  avatar: "css/images/avatar.png"
  date_format: "02-01-2006"
  readmore: true
  post_navigation: true
  postSections: ["blog"]
  copyright: "Copyright &copy; Stichting TkkrLab"
  logo: images/tkkrlab.svg
  logo_width: 100px
  mobile: 0124857985320
  email: info@tkkrlab.nl
  location: 'Rigtersbleek-zandvoort 10, 7521BE Enschede'
  contact_form_action: '#'
  google_analitycs_id: 'UA-610785-7'
  multi_author: false
  widgets:
    search: false
    recent_articles: true
    recent_articles_num: 5
    tags: true
    tags_counter: false
    newsletter: true
    contact: true
    meta: true
    twitter: true
    social_facebook: "TkkrLab"
    social_twitter: "tkkrlab"
    social_github: "tkkrlab"
    social_youtube: "TkkrLab"
    social_linkedin: "company/tkkrlab/"

  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
        attributes: media='screen'
      - link: plugins/Ionicons/css/ionicons.min.css
        attributes: ''
      - link: plugins/magnific-popup/magnific-popup.min.css
        attributes: ''
      - link: plugins/slick/slick.css
        attributes: ''
    js:
      - link: plugins/jQuery/jquery.min.js
        attributes: ''
      - link: plugins/bootstrap/bootstrap.min.js
        attributes: ''
      - link: plugins/slick/slick.min.js
        attributes: ''
      - link: plugins/magnific-popup/magnific-popup.min.js
        attributes: ''
      - link: plugins/shuffle/shuffle.min.js
        attributes: ''
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
  preloader:
    enable: false
    preloader: ''
  nav_button:
    enable: true
    label: Get A Quote
    link: contact
  gmap:
    enable: false
  cookies:
    enable: false
  social:
    - icon: ion-social-googleplus-outline
      link: '#'
    - icon: ion-social-linkedin-outline
      link: '#'
    - icon: ion-social-pinterest-outline
      link: '#'
    - icon: ion-social-dribbble-outline
      link: '#'
    - icon: ion-social-twitter-outline
      link: '#'
    - icon: ion-social-facebook-outline
      link: '#'

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/blog/"
      weight: 2
    - name: "Cybersaturday"
      url: "/cybersaturdays/cybersaturday"
      weight: 3
    - name: "Projecten"
      url: "/projects"
      weight: 7
    - name: "Deelnemer worden"
      url: "/deelnemer-worden"
      weight: 10
    - name: "Info"
      identifier: "info"
      url: "#"
      weight: 7
    - name: "Grafana: space statistieken"
      parent: "info"
      url: "https://grafana.tkkrlab.space"
      weight: 10
    - name: "How To's en handleidingen"
      parent: "info"
      url: "https://handleidingen.tkkrlab.space"
      weight: 11 
    - name: "Arduino cursus"
      parent: "info"
      url: "https://arduino.tkkrlab.space"
      weight: 12

Languages:
  nl:
    languageName: Nederlands
    languageCode: nl-nl
    weight: 1
  en:
    languageName: English
    languageCode: en-us
    weight: 2
  de:
    languageName: Deutsch
    languageCode: de-de
    weight: 3
