baseurl = "/"
languageCode = "nl-NL"
defaultContentLanguage = "nl"
title = "TkkrLab"
paginate = 5
#theme = "tkkrlab"
theme = "tkkrlab-mainroad"

logo = "/site_header.png"

enableRobotsTXT = false
#SectionPagesMenu = "main"
canonifyURLs = true

googleAnalytics = "UA-610785-7"

[markup]
  defaultMarkdownHandler = "blackFriday"


[Params]
  subtitle = "Makerspace Enschede"
  description = "TkkrLab hackerspace"
  powered_by = ""
  hide_author = true
  images = []
  author = "TkkrLab"
  copyright = ""
  avatar = "css/images/avatar.png"
  date_format = "02-01-2006"
  readmore = true
  post_navigation = true
  postSections = ["blog"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
 
  [[menu.main]]  
    name = "Projecten"
    url = "/projects"
    weight = 7

  [[menu.main]]  
    name = "Info"
    identifier = "info"
    url = "#"
    weight = 7
    
  [[menu.main]]  
    name = "Grafana: space statistieken"
    parent = "info"
    url = "https://grafana.tkkrlab.space"
    weight = 10
    
   [[menu.main]]  
    name = "How To's en handleidingen"
    parent = "info"
    url = "https://handleidingen.tkkrlab.space"
    weight = 11
    
   [[menu.main]]  
    name = "Arduino cursus"
    parent = "info"
    url = "https://arduino.tkkrlab.space"
    weight = 12

  #[[menu.main]]
  #  name = "Wiki"
  #  url = "https://www.tkkrlab.nl/wiki"
  #  weight = 9

[Params.widgets]
    search = false
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    #categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false
    newsletter = true
    contact = true
    meta = true
    twitter = true
    social_facebook = "TkkrLab"
    social_twitter = "tkkrlab"
    social_github = "tkkrlab"
    social_youtube = "TkkrLab"
    social_linkedin = "company/tkkrlab/"
